---
# This playbook installs Firefox

- name: Install Firefox package
  dnf: name=firefox state=latest

- name: Download Adobe Release
  get_url:
    url=http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
    dest={{ temp_dir }}/adobe-release.rpm

- name: Install Adobe Release
  dnf: name={{ temp_dir }}/adobe-release.rpm state=present

- name: Download Flash Player
  get_url:
    url=https://fpdownload.macromedia.com/get/flashplayer/pdc/11.2.202.540/flash-plugin-11.2.202.540-release.x86_64.rpm
    dest={{ temp_dir }}/flashplayer.rpm

- name: Install Flash Player
  dnf: name={{ temp_dir }}/flashplayer.rpm state=present
