---
# This playbook installs Google-Chrome apps

# create desktop entry for Workflowy
- name: Creating XFCE desktop entry for Workflowy app
  file: >
    src=files/workflowy.desktop
    dest=/usr/share/applications/workflowy.desktop
    owner=root
    group=root
    mode=0644