---
- name: Fedex provisioner
  hosts: localhost
  sudo: yes

  roles:
    - prepare_env
    - packages
    - git
    - oh-my-zsh
    - tmuxinator
    - guake
    - dropbox
    - skype
    - libreoffice
    - vlc
    - firefox
    - virtualbox
    - google-chrome
    - docker
    - steam
    - hstr
    - wireshark
    - sysdig
    - vim
    - slack
