---
- name: Fedex provisioner
  hosts: localhost
  sudo: yes
  vars:
    temp_dir: /tmp

  roles:
    - prepare_env
    - packages
    - dropbox
    - skype
    - libreoffice
    - vlc
    - firefox
    - virtualbox
    - google-chrome
