---
- name: Fedex provisioner
  hosts: localhost
  sudo: yes

  tasks:
    - include: tasks/pkg_update.yml
    - include: tasks/pkg_common_install.yml

  roles:
    - dropbox
    - skype
    - libreoffice
    - vlc
    - firefox
    - virtualbox
    - google-chrome
