---
- name: Install prerequisites
  yum: name=meld state=latest
- name: Configure git
  template:
    dest={{ home_dir }}/.gitconfig
    src=gitconfig
    owner={{ user }}
    group={{ group }}
    mode=0600
