---
# This playbook installs Slack client on Fedora

- name: Install npm
  yum: name=npm state=present

- name: Install Slack client from npm
  npm: >
    name=plaidchat
    global=yes
    state=latest
