---
# This playbook installs pyenv on Fedora
# https://github.com/pyenv/pyenv
- name: Install prerequisities
  dnf:
    name: "{{ pkg_list }}"
    state: present
  vars:
    pkg_list: ["zlib-devel", "bzip2", "bzip2-devel", "readline-devel", "sqlite", "sqlite-devel", "openssl-devel",
                  "xz", "xz-devel", "libffi-devel", "findutils"]

- block:
  - name: Clone repo
    git:
      repo: https://github.com/pyenv/pyenv.git
      dest: "{{ local_soft_dir }}/pyenv"
      update: no

  - name: Install plugins
    git:
      repo: "{{ item.url }}"
      dest: "{{ local_soft_dir }}/pyenv/plugins/{{ item.name }}"
      update: no
    loop:
    - url: "https://github.com/pyenv/pyenv-virtualenv.git"
      name: "pyenv-virtualenv"

  - name: "Update zshrc"
    lineinfile:
      path: "{{ home_dir}}/.zshrc"
      line: "{{ item.line }}"
      regexp: "{{ item.regexp }}"
    loop:
    - line: "export PYENV_ROOT=\"{{ local_soft_dir }}/pyenv\""
      regexp: "^export PYENV_ROOT"
    - line: 'export PATH="$PYENV_ROOT/bin:$PATH"'
      regexp: '^export PATH\=\"\$PYENV'

  become: no