---
# This playbook installs Docker

- name: Install Docker package
  yum: name=docker-io state=latest

- name: Add user to dockerroot group
  command: usermod -a -G dockerroot {{ user }}

- name: Switch to OverlayFS storage backend
  lineinfile:
    dest=/etc/sysconfig/docker-storage
    state=present
    regexp="^DOCKER_STORAGE_OPTIONS=(.*)(--storage-driver=.*\s*)*(.*)$"
    line='DOCKER_STORAGE_OPTIONS=\1 --storage-driver=overlay \3'
    backrefs=yes

- name: Restart Docker service
  service:
    name=docker
    state=restarted
